# template for deploying a new preview environment for each PR
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{.APP_ID}}"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: previews
  source:
    path: helm
    # should point to app repo you want to deploy from ie. node-hello-world
    repoURL: https://github.com/quinnstonchurchill/node-hello-world.git
    targetRevision: HEAD
    helm:
      values: |
        image:
          tag: "{{.IMAGE_TAG}}"
        ingress:
          host: "{{.HOSTNAME}}"
      version: v3
  destination:
    namespace: "{{.APP_ID}}"
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
