# ArgoCD AppProject that allows ArgoCD to create namespaces starting with pr-*
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: web-previews
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Previews
  sourceRepos:
    - "*"
  destinations:
    - namespace: web-previews
      server: https://kubernetes.default.svc
    - namespace: "web-pr-*"
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
